runtime: nodejs20
env: standard

instance_class: F2

env_variables:
  DB_HOST: 'goseneye:europe-west9:goseneye'
  DB_USER: 'cedricbatina'
  DB_PASSWORD: 'Elijahbatina2008'
  DB_NAME: 'goseneye'
  SMTP_HOST: 'smtp-relay.brevo.com'
  SMTP_PORT: '587'
  SMTP_USER: '7a753e001@smtp-brevo.com'
  SMTP_PASS: 'v9mtPW3aR1BzGkxK'
  EMAIL_FROM: 'cedricbatina2021@gmail.com'
  EMAIL_TO: 'cedricbatina2021@gmail.com'
  BASE_URL: 'http://localhost:3000'
  JWT_SECRET: 'goseneye_secret_key'
  YOUTUBE_API_KEY: 'AIzaSyBXYvmmUnfI79woin-DskfcIIhYbF0mW4k'
  GOOGLE_ANALYTICS_ID: 'G-LN39B54YL8'

beta_settings:
  cloud_sql_instances: 'goseneye:europe-west9:goseneye'

handlers:
  - url: /.*
    script: auto
